<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Reports;


class ReportsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Reports::truncate();
        $admins = [
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/start-now',
                'type' => 'meta-title',
                'data' => '{"name":"title","content":"Setmore | Free Online Appointment Scheduling Software", "casing": "Camel Case", "equal_h1": true, "duplicate": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/pricing',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Pricing | Setmore", "casing": "Camel Case", "equal_h1": false, "equal_h1_status": false, "duplicate": false, "duplicate_status": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/premium',
                'type' => 'meta-title',
                'data' => '{"name":"title","content":"Get Advanced Booking Features With Premium & Pro | Setmore", "casing": "Sentence Case", "equal_h1": true, "duplicate": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/faqs',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Frequently Asked Questions | Setmore", "casing": "Sentence Case", "equal_h1": false, "equal_h1_status": true, "duplicate": true, "duplicate_status": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/tour',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Take a Tour & Transform Your Booking Process | Setmore", "casing": "No Casing", "equal_h1": true, "equal_h1_status": true, "duplicate": true, "duplicate_status": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/our-mission',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Deliver Your Magic | Our Mission | Setmore", "casing": "Sentence Case", "equal_h1": false, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/ipad',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free iPad Appointment Scheduler | Setmore", "casing": "No Casing", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/free-business-website',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Business Website Builder With Online Booking | Setmore", "casing": "Sentence Case", "equal_h1": true, "equal_h1_status": true, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/square-payment/us',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Get Paid for Appointments With Square | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/online-scheduling',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Online Scheduling Tool For Your Business | Setmore", "casing": "Sentence Case", "equal_h1": false, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/facebook',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Get Your Free Facebook Booking System | Setmore", "casing": "No Casing", "equal_h1": false, "equal_h1_status": false, "duplicate": false, "duplicate_status": false}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/teleport',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Video Appointment Scheduling Software | Setmore", "casing": "Sentence Case", "equal_h1": true, "equal_h1_status": true, "duplicate": false, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/whats-your-resolution',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Start Now & Create Your Own Online Booking Calendar | Setmore", "casing": "No Casing", "equal_h1": false, "equal_h1_status": true, "duplicate": false, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/diary-management',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Diary Management | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/customers-across-timezones',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Get Your Free International Time Zone Scheduler | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/eliminate-fake-appointments',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Eliminate Fake Online Customer Appointments Today | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/online-agenda-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Agenda Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/online-booking-diary-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking Diary | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/online-scheduling-assistant',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Scheduling Assistant | Setmore", "casing": "Sentence Case", "equal_h1": false, "equal_h1_status": false, "duplicate": false, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/home',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"See How Simple Scheduling Can Be? | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/badges',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Showcase Your Success With Setmore Badges | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/square-promo',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Square Promo: Get Booked, Get Paid. 24/7. | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Features To Make Customer Booking Easy & Memorable | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/desktop-app',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Desktop Booking App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": false, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/payments/aus',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking And Payment System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/payments/ca',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking And Payment System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/payments/uk',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking And Payment System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": false, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/payments/us',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking And Payment System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/android-app',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Android Appointment Scheduling App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/ios-app',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Appointment Scheduling App For IPhone | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/schedule-virtual-meetings',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Schedule Virtual Meetings Online | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/recurring-appointments',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Schedule Recurring Appointments With Customers | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/appointments',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Manage Your Appointments With A Free Web Calendar | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/reviews',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Get Customer Reviews Online | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/google-calendar-sync',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Sync Your Setmore & Google Calendar Events | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/staff-scheduling',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Staff Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/email-reminders',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Automated Appointment Email Reminders | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/website-widgets',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Booking Widget For Your Website | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/text-reminders',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Send Automated Text Reminders For Appointments | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/booking-page',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Take Appointments 24/7 With An Online Booking Page | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/class-booking',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Online Class Scheduling Software For Group Sessions | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/features/qr-code-appointment-booking',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free QR Code For Appointment Booking | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Simple Scheduling Solutions For Every Industry | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/it-scheduling-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Scheduling Software For IT Professionals | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/teachers',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free School Scheduling Software For Teachers | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/vaccination-scheduling',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Vaccination Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/medical-appointment-scheduling-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Medical Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/doctors',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Doctor Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/accountants',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Scheduling Software For Accountants | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/tattoo-studios',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Tattoo Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/clio',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Centralize Client Data With The Clio Integration | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/wedding-boutiques',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Wedding Dress Appointment Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/financial-services',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Financial Services Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/pet-service',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Pet Grooming App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/massage-therapy',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Massage Booking App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/interview-scheduling',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Interview Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/salon',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Salon Booking System | Style More Clients! | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/home-repair',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Home Repair Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/tour-booking-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Tour Booking Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/consulting',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Consultant Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/counseling',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Counseling Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/pet-service',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Pet Grooming App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/automotive',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Automotive Appointment Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/chiropractor',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Chiropractic Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/real-estate',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Real Estate Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/online-tutoring',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Tutor Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/personal-trainer',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Personal Training Scheduling App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/dmv',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online DMV Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/gym',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Gym Scheduling Software | Fitness Class Scheduling | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/yoga',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Yoga Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/sales',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Sales Appointment Setting Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/retail-scheduling-software',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Retail Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/barber-shops',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Barber Appointment App | Barbershop Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/bridal-salon',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Bridal Salon Appointment Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/spa',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Spa Booking Software | Free Spa Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/dentist',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Dental Appointment Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/legal',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Legal Scheduling Software | Setmore", "casing": "No Casing", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/photography',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Photography Booking Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/nail-salon',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Nail Salon Scheduling Software | Nail Salon App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/embassies',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Booking Software For Embassies | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/industries/physical-therapy',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Online Physical Therapy Scheduling Software | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Integrations With The Worlds Most Popular Apps | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/insightly',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Import Contacts To Insightly From Your Booking System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/mailerlite',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Export Contacts To MailerLite Automatically | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/constant-contact',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Export Customer Contacts To Constant Contact | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/answerconnect',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"24/7 Call Answering & Scheduling Service | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/serviceminder',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Sync Your Customer Contacts With ServiceMinder | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/freshsales',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Export Contacts to Freshworks Automatically | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/infusionsoft-by-keap',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Export Customer Contacts To Keap Automatically | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/slack',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Slack Calendar Integration | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/clio',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Import Customer Contacts Into Clio Automatically | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/lex-reception',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Qualify & Book More Leads with LEX Reception | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/partners',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Partner With Us To Make Some Noise | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/zoho-crm',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Import Contacts To Zoho CRM Automatically | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/quickbooks',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free QuickBooks Scheduling Software Integration | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/zapier',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Connect Your Online Booking System With Xero | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/google-tag-manager',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Track Visitor Activity On Your Online Booking Page FREE | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/drupal',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Drupal Appointment Scheduler | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/gmail',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Add Appointments From Gmail To Your Calendar | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/muse',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Adobe Muse Booking Widget | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/joomla',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Joomla Appointment Booking System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/zendesk',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Zendesk Booking App | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/square-online',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Get Bookings 24/7 From Your Square Online Store | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/instagram-booking',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Book Appointments Through Instagram For Free | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/weebly',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Free Weebly Appointment Booking System | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/google-cal',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Sync Google Calendar With Your Appointments | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
            [
                'user_id' => 1,
                'project_id' => 2,
                'ref_id' => '12345678',
                'url' => 'https://www.setmore.com/integrations/office-cal',
                'type' => 'meta-title',
                'data' => '{"status": true, "name":"title","content":"Office 365 Calendar Sync For Your Appointments | Setmore", "casing": "Camel Case", "equal_h1": true, "equal_h1_status": false, "duplicate": true, "duplicate_status": true}',
            ],
        ];

        foreach($admins as $admin)
        {
            Reports::create([
                'user_id' => $admin['user_id'],
                'project_id' => $admin['project_id'],
                'ref_id' => $admin['ref_id'],
                'url' => $admin['url'],
                'type' => $admin['type'],
                'data' => $admin['data'],
            ]);
        }
    }
}
