<?php
namespace App\Http;

use Goutte\Client;
use Symfony\Component\HttpClient\HttpClient;
use Illuminate\Support\Facades\Http;
use Symfony\Component\DomCrawler\Crawler;
use GuzzleHttp\Client as GuzzleClient;
use DOMDocument;
use Illuminate\Support\Str;
use Exception;
use DOMXPath;

class AllLabels{
    function getAllLabels($project_id, $user_id){
        $meta = array (
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/title",
                'reportsUrl' => "/reports/meta-title",
                'display_name' => 'Meta Title',
                'name' => 'title',
                'db_name' => 'meta_title',
                'url' => '/test/title',
                'slug' => 'meta-title',
                'route' => 'tool/meta-title',
                'main_heading' => 'Meta Title Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/broken-links",
                'reportsUrl' => "/reports/broken-links",
                'display_name' => 'Broken Links',
                'name' => 'broken_links',
                'db_name' => 'broken_links',
                'url' => '/test/broken-links',
                'slug' => 'broken-links',
                'route' => 'tool/broken-links',
                'main_heading' => 'Broken Links Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/description",
                'reportsUrl' => "/reports/description",
                'display_name' => 'Meta Description',
                'name' => 'description',
                'db_name' => 'meta_desc',
                'url' => '/test/description',
                'slug' => 'meta-description',
                'route' => 'tool/meta-description',
                'main_heading' => 'Meta Description Test',
                'main_para' => 'Test your website pages for Meta description tag content and meta description length.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/canonical-url",
                'reportsUrl' => "/reports/canonical",
                'display_name' => 'Canonical URL',
                'name' => 'canonical',
                'db_name' => 'canonical_url',
                'url' => '/test/canonical-url',
                'slug' => 'canonical-url',
                'route' => 'tool/canonical-url',
                'main_heading' => 'Canonical URL Test',
                'main_para' => 'Test your website pages for canonicalisation, check whether they are self canonicalised or whether a canonical tag exists or not.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/robots-meta",
                'reportsUrl' => "/reports/robots-meta",
                'display_name' => 'Robots Meta Tag',
                'name' => 'robots',
                'db_name' => 'robots_meta',
                'url' => '/test/robots-meta',
                'slug' => 'robots-meta',
                'route' => 'tool/robots-meta',
                'main_heading' => 'Robots Meta Tag Test',
                'main_para' => 'Test your website pages for indexability, whether it contains a robots meta tag and the content of the robots meta tag.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/images",
                'reportsUrl' => "/reports/images",
                'display_name' => 'Images',
                'name' => 'img',
                'db_name' => 'images',
                'url' => '/test/images',
                'slug' => 'images',
                'route' => 'tool/images',
                'main_heading' => 'Images Test',
                'main_para' => 'Test multiple URLs for Images used in those URLs. Test Image alternate text, file size, file name and download the data in PDF or CSV Formats.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => false,
            ),    
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/url-slug",
                'reportsUrl' => "/reports/url-slug",
                'display_name' => 'URL Slug',
                'name' => 'url',
                'db_name' => 'url_slug',
                'url' => '/test/url-slug',
                'slug' => 'url-slug',
                'route' => 'tool/url-slug',
                'main_heading' => 'URL Slug Test',
                'main_para' => 'Test your website pages URL slug and check whether it meets best SEO practices and standards.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 0,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 0,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),  
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/xml-sitemap",
                'reportsUrl' => "/reports/xml-sitemap",
                'display_name' => 'XML Sitemap',
                'name' => 'xml_sitemap',
                'db_name' => 'xml_sitemap',
                'url' => '/test/xml-sitemap',
                'slug' => 'xml-sitemap',
                'route' => 'tool/xml-sitemap',
                'main_heading' => 'XML Sitemap Test',
                'main_para' => 'Test your website pages if they exist in the XML Sitemap',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/html-sitemap",
                'reportsUrl' => "/reports/html-sitemap",
                'display_name' => 'HTML Sitemap',
                'name' => 'html_sitemap',
                'db_name' => 'html_sitemap',
                'url' => '/test/html-sitemap',
                'slug' => 'html-sitemap',
                'route' => 'tool/html-sitemap',
                'main_heading' => 'HTML Sitemap Test',
                'main_para' => 'Test your website pages if they exist in the HTML Sitemap',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/og-tags",
                'reportsUrl' => "/reports/og-tags",
                'display_name' => 'Open Graph Tags',
                'name' => 'og:title',
                'db_name' => 'open_graph_tags',
                'url' => '/test/og-tags',
                'slug' => 'og-tags',
                'route' => 'tool/og-tags',
                'main_heading' => 'Open Graph Tags Test',
                'main_para' => 'Test your website pages for Open Graph Tags tags, whether they exist and are following the best practices and standards.',
                'results_heading' => 'Open Graph Tags',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'ogDesc' => [
                    'display_name' => "OG Description",
                    'name' => "og:description",
                    'db_name' => "open_graph_desc",
                ],
                'ogImage' => [
                    'display_name' => "OG Image",
                    'name' => "og:image",
                    'db_name' => "open_graph_image",
                ],
                'ogURL' => [
                    'display_name' => "OG URL",
                    'name' => "og:url",
                    'db_name' => "open_graph_url",
                ],
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/twitter-tags",
                'reportsUrl' => "/reports/twitter-tags",
                'display_name' => 'Twitter Tags',
                'name' => 'twitter:title',
                'db_name' => 'twitter_tags',
                'url' => '/test/twitter-tags',
                'slug' => 'twitter-tags',
                'route' => 'tool/twitter-tags',
                'main_heading' => 'Twitter Tags Test',
                'main_para' => 'Test your website pages for Twitter title tags, whether they exist and are following the best practices and standards.',
                'results_heading' => 'Twitter Tags',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'twitterImage' => [
                    'display_name' => "Twitter Image",
                    'name' => "twitter:image",
                    'db_name' => "twitter_image",
                ],
                'twitterImageAlt' => [
                    'display_name' => "Twitter Image Alt",
                    'name' => "twitter:image:alt",
                    'db_name' => "twitter_image_alt",
                ],
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/favicon",
                'reportsUrl' => "/reports/favicon",
                'display_name' => 'Favicon',
                'name' => 'icon',
                'db_name' => 'favicon',
                'url' => '/test/favicon',
                'slug' => 'favicon',
                'route' => 'tool/favicon',
                'main_heading' => 'Favicon Test',
                'main_para' => 'Test your website pages if they are using a Favicon tag or not.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 0,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 0,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
    
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/meta-viewport",
                'reportsUrl' => "/reports/meta-viewport",
                'display_name' => 'Meta Viewport',
                'name' => 'viewport',
                'db_name' => 'meta_viewport',
                'url' => '/test/meta-viewport',
                'slug' => 'meta-viewport',
                'route' => 'tool/meta-viewport',
                'main_heading' => 'Meta Viewport Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 0,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 0,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/doctype",
                'reportsUrl' => "/reports/doctype",
                'display_name' => 'Doctype',
                'name' => 'doctype',
                'db_name' => 'doctype',
                'url' => '/test/doctype',
                'slug' => 'doctype',
                'route' => 'tool/doctype',
                'main_heading' => 'Doctype Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 0,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 0,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/http-status-code",
                'reportsUrl' => "/reports/http-status-code",
                'display_name' => 'HTTP Status Code',
                'name' => 'http_status_code',
                'db_name' => 'http_status_code',
                'url' => '/test/http-status-code',
                'slug' => 'http-status-code',
                'route' => 'tool/http-status-code',
                'main_heading' => 'HTTP Status Code Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'seo',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/google-page-speed-insights",
                "reportsUrl" => "/reports/google-page-speed-insights",
                'display_name' => 'Overall Score',
                'name' => 'page_speed_google',
                'db_name' => 'google_overall',
                'url' => '/test/google-page-speed-insights',
                'slug' => 'google-page-speed-insights',
                'route' => 'tool/google-page-speed-insights',
                'main_heading' => 'Google Page Speed - Overall Score Test',
                'main_para' => 'Test multiple URLs for Google Page speed overall score. Download scores in CSV or PDF file.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'performance',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/google-page-speed-lighthouse",
                "reportsUrl" => "/reports/google-page-speed-lighthouse",
                'display_name' => 'Lighthouse Score',
                'name' => 'page_speed_google_lighthouse',
                'db_name' => 'google_lighthouse',
                'url' => '/test/google-page-speed-lighthouse',
                'slug' => 'google-lighthouse',
                'route' => 'tool/google-lighthouse',
                'main_heading' => 'Lighthouse Test',
                'main_para' => 'Test multiple URLs for Lighthouse scores and Download them in CSV or PDF file format.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'performance',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/google-page-speed-core-web-vitals",
                "reportsUrl" => "/reports/google-page-speed-core-web-vitals",
                'display_name' => 'Core Web Vitals',
                'name' => 'page_speed_google_core',
                'db_name' => 'core_web_vitals',
                'url' => '/test/google-page-speed-core-web-vitals',
                'slug' => 'google-core-web-vitals',
                'route' => 'tool/google-core-web-vitals',
                'main_heading' => 'Core Web Vitals Test',
                'main_para' => 'Test multiple URLs for Core web vitals score and Download them in CSV or PDF file format.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'performance',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/mobile-friendly",
                "reportsUrl" => "/reports/mobile-friendly",
                'display_name' => "Mobile Friendly",
                'name' => "mobile_friendly",
                'db_name' => "mobile_friendly",
                'url' => "/test/mobile-friendly",
                'slug' => 'mobile-friendly',
                'route' => 'tool/mobile-friendly',
                'main_heading' => 'Mobile Friendly',
                'main_para' => 'Mobile Friendly Test multiple URLs for Core web vitals score and Download them in CSV or PDF file format.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'performance',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/x-frame-options-header",
                "reportsUrl" => "/reports/x-frame-options-header",
                'display_name' => 'X Frame Options Header',
                'name' => 'xframe',
                'db_name' => 'x_frame_options_header',
                'url' => '/test/x-frame-options-header',
                'slug' => 'x-frame-options-header',
                'route' => 'tool/x-frame-options-header',
                'main_heading' => 'X Frame Options Header',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/content-security-policy-header",
                'display_name' => 'Content Security Policy Header',
                'name' => 'content-security',
                'db_name' => 'content_security_policy_header',
                'url' => '/test/content-security-policy-header',
                'slug' => 'content-security-policy-header',
                'route' => 'tool/content-security-policy-header',
                'main_heading' => 'Content Security Policy Header',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/hsts-header",
                'display_name' => 'HSTS Header',
                'name' => 'hsts',
                'db_name' => 'hsts_header',
                'url' => '/test/hsts-header',
                'slug' => 'hsts-header',
                'route' => 'tool/hsts-header',
                'main_heading' => 'Hsts Header Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/bad-content-type",
                'display_name' => 'Bad Content Type',
                'name' => 'bad_content_type',
                'db_name' => 'bad_content_type',
                'url' => '/test/hsts-header',
                'slug' => 'bad-content-type',
                'route' => 'tool/bad-content-type',
                'main_heading' => 'Bad Content Type Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/safe-browsing",
                'display_name' => 'Safe Browsing',
                'name' => 'is_safe_browsing',
                'db_name' => 'is_safe_browsing',
                'url' => '/test/is-safe-browsing',
                'slug' => 'is-safe-browsing',
                'route' => 'tool/is-safe-browsing',
                'main_heading' => 'Directory Browsing Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/unsafe-cross-origin-links",
                'display_name' => 'Unsafe Cross Origin Links',
                'name' => 'cross_origin_links',
                'db_name' => 'cross_origin_links',
                'url' => '/test/hsts-header',
                'slug' => 'hsts-header',
                'route' => 'tool/hsts-header',
                'main_heading' => 'Unsafe Cross Origin Links Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/protocol-relative-resource",
                'display_name' => 'Protocol Relative Resource Links',
                'name' => 'protocol_relative_resource',
                'db_name' => 'protocol_relative_resource',
                'url' => '/test/protocol-relative-resource',
                'slug' => 'protocol-relative-resource',
                'route' => 'tool/protocol-relative-resource',
                'main_heading' => 'Protocol Relative Resource Links Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/ssl-certificate",
                'display_name' => 'SSL Certificate',
                'name' => 'ssl_certificate_enable',
                'db_name' => 'ssl_certificate_enable',
                'url' => '/test/ssl-certificate-enable',
                'slug' => 'ssl-certificate-enable',
                'route' => 'tool/ssl-certificate-enable',
                'main_heading' => 'SSL Certificate Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/directory-browsing",
                'display_name' => 'Directory Browsing',
                'name' => 'folder_browsing_enable',
                'db_name' => 'folder_browsing_enable',
                'url' => '/test/folder-browsing-enable',
                'slug' => 'folder-browsing-enable',
                'route' => 'tool/folder-browsing-enable',
                'main_heading' => 'Directory Browsing Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'bulk_ignore' => true,
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'security_labels',
                'parent' => 'security',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/html-compression",
                'display_name' => 'HTML Compression',
                'name' => 'compression',
                'db_name' => 'html_compression',
                'url' => '/test/html-compression',
                'slug' => 'html-compression',
                'route' => 'tool/html-compression',
                'main_heading' => 'HTML Compression Test',
                'main_para' => 'Test multiple urls for HTML Compression. Check which of your website pages do not have HTML compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/css-compression",
                'display_name' => 'CSS Compression',
                'name' => 'stylesheet',
                'db_name' => 'css_compression',
                'url' => '/test/css-compression',
                'slug' => 'css-compression',
                'route' => 'tool/css-compression',
                'main_heading' => 'CSS Compression Test',
                'main_para' => 'Test multiple urls CSS Compression. Check which of your website CSS files do not have compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/js-compression",
                'display_name' => 'JS Compression',
                'name' => 'script',
                'db_name' => 'js_compression',
                'url' => '/test/js-compression',
                'slug' => 'js-compression',
                'route' => 'tool/js-compression',
                'main_heading' => 'JS Compression Test',
                'main_para' => 'Test multiple website urls for JS Compression. Check which of your Javascript files do not have compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/gzip-compression",
                'display_name' => 'Gzip Compression',
                'name' => 'gzip_compression',
                'db_name' => 'gzip_compression',
                'url' => '/test/gzip-compression',
                'slug' => 'gzip-compression',
                'route' => 'tool/gzip-compression',
                'main_heading' => 'Gzip Compression Test',
                'main_para' => 'Test your website pages for Gzip compression and see which one of them do not have Gzip compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
                ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/css-caching",
                'display_name' => 'CSS caching',
                'name' => 'css_caching_enable',
                'db_name' => 'css_caching_enable',
                'url' => '/test/css-caching-enable',
                'slug' => 'css-caching-enable',
                'route' => 'tool/css-caching-enable',
                'main_heading' => 'CSS caching',
                'main_para' => 'Test your website pages for Gzip compression and see which one of them do not have Gzip compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/js-caching",
                'display_name' => 'JS Caching',
                'name' => 'js_caching_enable',
                'db_name' => 'js_caching_enable',
                'url' => '/test/js-caching-enable',
                'slug' => 'js-caching-enable',
                'route' => 'tool/js-caching-enable',
                'main_heading' => 'JS caching',
                'main_para' => 'Test your website pages for Gzip compression and see which one of them do not have Gzip compression enabled.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
                            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/nested-tables",
                'display_name' => 'Nested Tables',
                'name' => 'nestedtables',
                'db_name' => 'nested_tables',
                'url' => '/test/nested-tables',
                'slug' => 'nested-tables',
                'route' => 'tool/nested-tables',
                'main_heading' => 'Nested Table Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'bulk_ignore' => true,
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/content-security-policy-header",
                "reportsUrl" => "/reports/frameset",
                'display_name' => 'Frameset',
                'name' => 'frameset',
                'db_name' => 'frameset',
                'url' => '/test/frameset',
                'slug' => 'frameset',
                'route' => 'tool/frameset',
                'main_heading' => 'Frameset Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 1,
                'dashboard_parent' => 'cbp_labels',
                'parent' => 'bestPractices',
                'bulk_ignore' => true,
                'initialTestingState' => true,
            ),
            array (
                'user_id' => $user_id,
                'project_id' => $project_id,
                'urlDetails' => "/test-details/page-size",
                "reportsUrl" => "/reports/page-size",
                'display_name' => 'Page Size',
                'name' => 'pagesize',
                'db_name' => 'page_size',
                'url' => '/test/page-size',
                'slug' => 'page-size',
                'route' => 'tool/page-size',
                'main_heading' => 'Page Size Test',
                'main_para' => 'Test your website pages for Meta title tag content. Check meta title length, whether it is equal to H1 tag, and check what casing the title tag follows.',
                'results_heading' => 'Results',
                'results_para' => 'Results',
                'is_dashboard_status' => 1,
                'analysis_status' => 1,
                'bulk_status' => 1,
                'show_dashboard_status' => 1,
                'has_dashboard_parent' => 0,
                'dashboard_parent' => '',
                'parent' => 'bestPractices',
                'initialTestingState' => true,
            ),
        );

        return $meta;
    }
}   